In [ ]:
import numpy as np
a = np.empty((2,2))
a

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

In [ ]:
a = np.empty((4,3))
a

array([[5.06397028e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
a = np.full((2,2),3)
a



array([[3, 3],
       [3, 3]])

In [ ]:
y = np.arange(4, dtype=int)
np.full_like(y, 2)

array([2, 2, 2, 2])

In [ ]:
y = np.arange(6, dtype=float)
y
np.ones_like(y)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
a = ([1,2,3,4])
a
y = np.array([a])
y

array([[1, 2, 3, 4]])

In [ ]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.eye(6, dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [ ]:
y = np.random.random(30)
y
a = y.mean()
a


0.531772453926737

In [ ]:
a = np.random.rand(10,10)
a

array([[0.48741273, 0.41624898, 0.72558085, 0.29978246, 0.0066268 ,
        0.09930184, 0.27204691, 0.29289639, 0.84219376, 0.24377969],
       [0.82841136, 0.38918817, 0.69391224, 0.34271405, 0.94263448,
        0.94060481, 0.23926182, 0.16564847, 0.89912611, 0.93524603],
       [0.39792661, 0.88841557, 0.01409008, 0.61190952, 0.21225695,
        0.00140062, 0.11311291, 0.96236286, 0.94201801, 0.46842577],
       [0.34103078, 0.06091855, 0.36620746, 0.19432666, 0.21689614,
        0.97460355, 0.90558634, 0.72331741, 0.84523904, 0.94720267],
       [0.09997666, 0.58075692, 0.9473801 , 0.86458704, 0.88514502,
        0.50563977, 0.49468761, 0.4552733 , 0.36775823, 0.80699656],
       [0.80560158, 0.50734085, 0.44214042, 0.14547782, 0.69890473,
        0.27378425, 0.78203648, 0.461267  , 0.13609869, 0.98014249],
       [0.13485038, 0.48771823, 0.57137097, 0.95304978, 0.40164405,
        0.00475287, 0.18997773, 0.38568899, 0.16421721, 0.71941892],
       [0.59433462, 0.33223124, 0.9424625

In [ ]:
y = np.zeros(10)
y[4]=1
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
a =np.array([1,2,0,0,4,0])
y=np.flip(a)
y


array([0, 4, 0, 0, 2, 1])

In [ ]:
a = np.ones((8,8))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
a = np.ones((8,8))
a[1::2,1::2]=0
a[::2,::2]=0
a


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
# 1. Add the two arrays
add_result = x + y
print("1. Addition of x and y:\n", add_result)

In [ ]:
# 2. Subtract the two arrays
subtract_result = x - y
print("\n2. Subtraction of x and y:\n", subtract_result)

In [ ]:
# 3. Multiply the array `x` by an integer (e.g., 3)
multiply_result = x * 3
print("\n3. Multiplication of x by 3:\n", multiply_result)

In [ ]:
# 4. Find the square of each element in `x`
square_result = np.square(x)
print("\n4. Square of each element in x:\n", square_result)

In [ ]:
# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)  # This is valid because `v` can act as a column vector
dot_xy = np.dot(x, y)
print("\n5. Dot products:")
print("   Dot product of v and w:", dot_vw)
print("   Dot product of x and v:\n", dot_xv)
print("   Dot product of x and y:\n", dot_xy)


In [ ]:
# 6. Concatenate `x` and `y` along rows
concat_xy_row = np.concatenate((x, y), axis=0)
print("\n6. Concatenate x and y along rows:\n", concat_xy_row)

In [ ]:
# Concatenate `v` and `w` along columns
concat_vw_column = np.column_stack((v, w))
print("\n6. Concatenate v and w along columns:\n", concat_vw_column)

In [ ]:
# 7. Attempt to concatenate `x` and `v` (observe the error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print("\n7. Concatenate x and v resulted in an error:")
    print(e)


In [ ]:
# Define the matrices
A = np.array([[3, 4], [7, 8]])

In [ ]:
# Compute the inverse of A
A_inv = np.linalg.inv(A)

In [ ]:
# Multiply A with its inverse
result = np.dot(A, A_inv)

In [ ]:
# Print the result
print("A * A^(-1) =\n", result)

In [ ]:
# Define the second matrix
B = np.array([[5, 3], [2, 1]])

In [ ]:
# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

In [ ]:
# Print both results
print("AB =\n", AB)
print("BA =\n", BA)

In [ ]:
# Compute (AB)^T
AB_T = np.transpose(AB)

In [ ]:
# Compute B^T A^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))

In [ ]:
# Print both results
print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)

In [ ]:
# Define the coefficient matrix A and the constant matrix B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

In [ ]:
# Compute the solution using the inverse method
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

In [ ]:
# Print the solution
print("Solution X =\n", X)

In [ ]:
# Solve the linear equations using np.linalg.solve
X_solve = np.linalg.solve(A, B)


In [ ]:
# Print the solution
print("Solution using np.linalg.solve X =\n", X_solve)
